{{- if index .Values "adb-maintainer-operator" "enabled" }}
{{- if .Capabilities.APIVersions.Has "olympus.genomics.roche.com/v0alpha1" -}}
# Empty ArtifactDB manifest, just a place-holder.
apiVersion: olympus.genomics.roche.com/v0alpha1
kind: ArtifactDB
metadata:
  name: {{ include "adb.name" . }}
  namespace: {{ include "adb.namespace" . }}
spec:
  active: false
{{- else }}
{{- fail "Olympus isn't installed, can't use ArtifactDB manifest" }}
{{- end }}
{{- end }}
