# Flower deployment (Celery UI)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adb.fullname" . }}-flower
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "adb.labels" . | nindent 4 }}
    component: flower
  namespace: {{ include "adb.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "adb.selectorLabels" . | nindent 6 }}
      component: flower
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        {{- include "adb.selectorLabels" . | nindent 8 }}
        component: flower
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - flower
        {{- with .Values.rabbitmq.auth }}
        - "--broker=pyamqp://{{- .username }}:{{- .password }}@rabbitmq"
        {{- end }}
        - "--port={{- .Values.backend.service.port }}"
        - --address=0.0.0.0
        - --url_prefix={{ include "adb.api_prefix" . }}/flower
        image: {{ .Values.flower.image }}
        name: flower
        ports:
        - containerPort: {{ .Values.backend.service.port }}  # same as celery backend

---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "adb.labels" . | nindent 4 }}
  name: {{ include "adb.fullname" . }}-flower
  namespace: {{ include "adb.namespace" . }}
spec:
  ports:
  {{- with .Values.flower.service }}
  - port: {{ .port }}
    {{- if contains "NodePort" .type }}
    nodePort: {{ .nodePort }}
    {{- end }}
    protocol: TCP
    targetPort: {{ .targetPort }}
  type: {{ .type }}
  {{- end }}
  selector:
    {{- include "adb.selectorLabels" . | nindent 4 }}
    component: flower
