{{- if .Values.network_policy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: limit-ingress
spec:
  podSelector: {}
  ingress:
  - from:
      # allow pods within the instance namespace to communicate with each others
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ include "adb.namespace" . }}
      {{ if .Values.network_policy.ingress_namespace }}
      # allows ingress controller to route requests
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Values.network_policy.ingress_namespace }}
      {{ end }}
  policyTypes:
  - Ingress
{{- end }}

